DOKUMEN = [
    {"id": "D01", "judul": "Kecerdasan Buatan",
     "teks": "Kecerdasan buatan memungkinkan komputer belajar dari data dan membuat keputusan layaknya manusia. Algoritma pembelajaran mesin digunakan untuk melatih model dari kumpulan data besar."},
    {"id": "D02", "judul": "Keamanan Siber",
     "teks": "Keamanan siber melindungi sistem komputer dari serangan peretas dan virus berbahaya. Enkripsi data adalah teknik utama untuk menjaga kerahasiaan informasi pengguna."},
    {"id": "D03", "judul": "Internet of Things",
     "teks": "Internet of Things menghubungkan perangkat elektronik melalui jaringan internet. Perangkat rumah tangga dapat dikendalikan dari jarak jauh menggunakan aplikasi smartphone."},
    {"id": "D04", "judul": "Pendidikan Digital",
     "teks": "Platform e-learning menyediakan akses pendidikan tanpa batas geografis. Siswa dapat belajar kapan saja melalui video pembelajaran dan kuis interaktif secara online."},
    {"id": "D05", "judul": "Peran Guru",
     "teks": "Guru berperan penting membentuk karakter siswa di sekolah. Selain menyampaikan materi pelajaran, guru juga membimbing siswa menghadapi tantangan kehidupan sehari-hari."},
    {"id": "D06", "judul": "Kesehatan Digital",
     "teks": "Aplikasi kesehatan digital membantu pemantauan kondisi tubuh secara real-time. Pasien dapat berkonsultasi dengan dokter melalui telemedicine tanpa harus datang ke rumah sakit."},
    {"id": "D07", "judul": "Olahraga dan Kesehatan",
     "teks": "Olahraga rutin menjaga kesehatan tubuh dan meningkatkan sistem kekebalan. Dokter menyarankan minimal tiga puluh menit olahraga setiap hari untuk mencegah penyakit jantung."},
    {"id": "D08", "judul": "Nutrisi dan Pola Makan",
     "teks": "Pola makan sehat dengan konsumsi sayuran dan buah menjaga kesehatan tubuh. Menghindari makanan berlemak tinggi dapat mencegah diabetes dan penyakit jantung koroner."},
    {"id": "D09", "judul": "Perubahan Iklim",
     "teks": "Perubahan iklim global disebabkan emisi gas rumah kaca dari aktivitas industri manusia. Negara-negara dunia harus bekerja sama mengurangi emisi karbon dioksida ke atmosfer bumi."},
    {"id": "D10", "judul": "Energi Terbarukan",
     "teks": "Energi surya dan angin menjadi solusi mengurangi ketergantungan pada bahan bakar fosil. Panel surya mengubah sinar matahari menjadi listrik bersih yang ramah lingkungan."},
    {"id": "D11", "judul": "Ekonomi Digital",
     "teks": "Ekonomi digital berkembang pesat seiring meningkatnya penggunaan internet di masyarakat. Platform e-commerce menghubungkan penjual dan pembeli dari seluruh penjuru dunia."},
    {"id": "D12", "judul": "Investasi Pasar Modal",
     "teks": "Investasi saham dan reksa dana adalah cara mengembangkan aset keuangan jangka panjang. Literasi keuangan penting agar investor dapat membuat keputusan investasi yang tepat."},
    {"id": "D13", "judul": "Budaya Nusantara",
     "teks": "Indonesia memiliki kekayaan budaya beragam dari Sabang sampai Merauke. Pelestarian tradisi dan kesenian lokal penting menjaga identitas bangsa di era globalisasi."},
    {"id": "D14", "judul": "Pariwisata Indonesia",
     "teks": "Keindahan alam dan budaya Indonesia menarik wisatawan dari seluruh dunia. Pengembangan infrastruktur pariwisata meningkatkan kualitas layanan dan pendapatan daerah."},
    {"id": "D15", "judul": "Penelitian Ilmiah",
     "teks": "Penelitian ilmiah menjadi fondasi kemajuan peradaban manusia di segala bidang ilmu. Kolaborasi universitas dan industri mendorong inovasi teknologi yang bermanfaat bagi masyarakat."},
    {"id": "D16", "judul": "Kendaraan Listrik",
     "teks": "Kendaraan listrik semakin populer sebagai solusi transportasi ramah lingkungan. Baterai lithium-ion digunakan untuk menyimpan energi dan menggerakkan motor listrik pada mobil maupun sepeda motor. Pengembangan infrastruktur pengisian daya menjadi kunci percepatan adopsi kendaraan listrik."},
    {"id": "D17", "judul": "Pertanian Modern",
     "teks": "Pertanian modern memanfaatkan teknologi sensor dan drone untuk memantau kondisi lahan secara presisi. Sistem irigasi otomatis membantu petani menghemat penggunaan air dan pupuk. Penerapan teknologi pertanian cerdas meningkatkan hasil panen dan mengurangi ketergantungan pada tenaga kerja manual."},
    {"id": "D18", "judul": "Kesehatan Mental",
     "teks": "Kesehatan mental sama pentingnya dengan kesehatan fisik dalam kehidupan manusia. Stres dan kecemasan berlebihan dapat mempengaruhi produktivitas dan kualitas hidup seseorang. Konseling psikologis dan meditasi terbukti efektif membantu pemulihan gangguan kesehatan mental."},
    {"id": "D19", "judul": "Blockchain dan Kripto",
     "teks": "Teknologi blockchain menyediakan sistem pencatatan data yang terdesentralisasi dan transparan. Mata uang kripto seperti Bitcoin menggunakan blockchain sebagai infrastruktur transaksi digital. Kontrak pintar memungkinkan eksekusi perjanjian otomatis tanpa memerlukan pihak ketiga sebagai perantara."},
    {"id": "D20", "judul": "Robotika dan Otomasi",
     "teks": "Robotika dan otomasi industri mengubah cara manusia bekerja di berbagai sektor produksi. Robot kolaboratif atau cobot dirancang untuk bekerja berdampingan dengan manusia di lini produksi. Otomasi proses bisnis meningkatkan efisiensi operasional dan mengurangi kesalahan akibat faktor manusia."},
]